// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mocutjvbgtutbraygwce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY3V0anZiZ3R1dGJyYXlnd2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkxMDExNDAsImV4cCI6MjA1NDY3NzE0MH0.3eB2F74eXwClYcykt8d5oe_4k76R-Mqf7rttMND0yaI";

// Import the supabase client like this:
// import { supabase } from "../../integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);